### ISSUE TITLE
 P2(website) 403 Forbidden Error

### ISSUE THREAD

**Issue by coeure-d-elephante** [susanBuck/e15-spring23#18]
Hi Professor,

The url for my project two shows this error. Below is the copy of the server configuration for this project. How can I fix this?

Please and thank you!
<img width="898" alt="Screenshot 2023-03-20 at 13 48 57" src="https://user-images.githubusercontent.com/78046295/226468468-e0f276fe-7fe3-4a7b-b278-9068d427a57e.png">
![unnamed](https://user-images.githubusercontent.com/78046295/226468617-9d03e2c2-df2d-4370-8936-1acb3fbd3c1f.png)

**Comment by susanBuck** [comment]
Hi @coeure-d-elephante -

An issue I see is in this line:

```
root /var/www/e15/p2;
```

With Laravel applications, the document root should point to the public folder within your project. So the line should be:

```
root /var/www/e15/p2/public;
```

Try making that change, restarting your server and seeing if it resolves the issue. If not, let me know!

**Comment by coeure-d-elephante** [comment]
Hello! @susanBuck 

thank you I made the changes, however I am encountering this problem when I run this command on the terminal
`ln -s /etc/nginx/sites-available/hes /etc/nginx/sites-enabled`

<img width="761" alt="Screenshot 2023-03-20 at 15 28 37" src="https://user-images.githubusercontent.com/78046295/226479146-2ca1d9a6-0fdf-41bb-8200-12a968c370e2.png">

Additionally, with the addition of 
`root /var/www/e15/p2/public;`
<img width="633" alt="Screenshot 2023-03-20 at 15 32 38" src="https://user-images.githubusercontent.com/78046295/226479749-3e1217ba-7d32-4b82-a860-b33f7d664883.png">



I am receiving this error. 
https://flareapp.io/share/V7j2jJL7#F11

**Comment by susanBuck** [comment]
The error for the symbolic link step indicates it already exists. This makes sense because it was a command we ran that command earlier in the semester. It only needed to be run once to initially set up that `hes`sites file. Now that it's set up, you don't need to set up the symbolic link again.

As for the permission error - Can you confirm you [ran the commands described in this step](https://hesweb.dev/e15/notes/laravel/new-laravel-app#permissions) within your application directory? The error you're seeing says it does not have permission to write to a file in the storage directory, so following the permission instructions should straighten that out.

**Comment by coeure-d-elephante** [comment]
Got it! Thanks!

The permission error was resolved when I copied the steps. Thank you!
