### ISSUE TITLE
P2 Problem Rendering Results and Default Check Box

### ISSUE THREAD

**Issue by coeure-d-elephante** [susanBuck/e15-spring23#20]
Hi,

My project is almost done.

I just need help with 2 main things:

1. I can't figure out the Default Check Box and I'm running into this error 
with this ternary operator:
`  {{ ($price == '') ? 'checked' : 'Enter value' }} `

i.e.: If $price has any input then 'check' the box. If not, uncheck.

https://flareapp.io/share/67OgOwv7#F54

<img width="493" alt="Screenshot 2023-03-21 at 21 17 14" src="https://user-images.githubusercontent.com/78046295/226800941-5a5a0a7c-0a04-4541-8ccf-3259973c41dd.png">

2. I'm encountering this bug when I render my results in an input box

https://flareapp.io/share/B5ZN2Wv5#F54

 ```
@if(!is_null($net_total))

        <div class='results alert alert-warning'>
            Please enter appropriate values.
        </div>
    @else
        <div class='results alert alert-primary'>
            <div>
                <label for='net_total'>Net Total</label>
                <input type='number' name='net_total' id='net_total' value='{{ $net_total }}'>
            </div>
        </div>
    @endif
   
```

**Comment by susanBuck** [comment]
## Problem 1
This error is occuring because on initial page load (before the form has been submitted), `$price` is not yet defined.

To avoid this error, you can expand the boolean expression to also check that price is set using PHP's [isset](https://www.php.net/manual/en/function.isset.php) function before checking its value:

```php
{{ (isset($price) && $price == '') ? 'checked' : '' }}
```


## Problem 2
Similar type of issue to Problem 1. The error is saying that `$net_total` is undefined because on initial page load before the form is submitted `$net_total` is not yet defined. 

To address, instead of:
```php
@if(!is_null($net_total))
```

Try:
```php
@if(!isset($net_total))
```

**Comment by coeure-d-elephante** [comment]
Thank you!

For Problem 1: Fixed the error, however, the check box remains unchecked.
```php
 {{ (isset($price) && $price == '') ? 'checked' : '' }}

```

For Problem 2: Fixed the error, however, the input is not working properly. The success notification won't render due to the value not rendering at all

 ```php
@if(!isset($net_total))
        <div class='results alert alert-warning'>
            Please enter appropriate values.
        </div>
    @else
        <div class='results alert alert-primary'>
            <div>
                <label for='net_total'>Net Total</label>
                <input type='number' name='net_total' id='net_total' value='view{{ \Request::get('net_total') }}'>
            </div>
        </div>
    @endif
```
I've passed back my variables with "->with" function

```php
return redirect('/')->with([
        'net_total' => $net_total,
        'price' => $price,
       ]);
```

**Comment by susanBuck** [comment]
## Problem 1 

Based on the boolean expression (`isset($price) && $price == ''`), two conditions have to be met for the `checked` attribute to be inserted:

1. `$price` is set
2. `$price` is equivalent to an empty string (`''`)

It doesn't look like it's possible for `$price` to ever be an empty string because if it is, validation will fail (you've specified that price = required) and it will bounce the user back to the index method.

Because of this, the boolean expression will never evaluate to true and the box will never be checked. 

To help you form what boolean expression you should be using I think I need to better understand your goal. Are you just trying to have the sales tax checkbox checked on initial page load before the form has been submitted?

## Problem 2

In this line you are attempting to retrieve a value from the request using the Request facade and a get method:

```php
<input type='number' name='net_total' id='net_total' value='view{{ \Request::get('net_total') }}'>
```

This is problematic for a couple reasons:

1. You should extract/handle any data in the controller and then pass it to the view.
2. Request::get will try and extract data from a form submission, but in this case you are trying to extract data that was flashed to the session:

```php
return redirect('/')->with([
    'net_total' => $net_total,
    'price' => $price,
]);
```

Revisiting the Bookmark example ([BookController@search](https://github.com/susanBuck/e15/blob/main/bookmark/app/Http/Controllers/BookController.php#L50) / [PageController@welcome](https://github.com/susanBuck/e15/blob/main/bookmark/app/Http/Controllers/PageController.php#L12)) and notes on [Redirects, sessions, and flash data](https://hesweb.dev/e15/notes/laravel/forms-get#redirects-sessions-and-flash-data) what you want to do in AppController@index is look for this session data and pass it to the view:

```php
 public function index()
{
        return view('pages/index')->with([
            'net_total' => session('net_total', null)
        );
}
```

Then you can display it in the view: 

```html
<input type='number' name='net_total' id='net_total' value='{{ $net_total }}'>
```

Note that with this change, `$net_total` will always be set when loading the index, it just might be null if the form has not been submitted yet. Because of this, you should revert to using the `is_null` instead of `isset` in the view when checking if `$net_total` is available.

Have a stab at the above tweaks and let me know how it goes. All of the above suggestions are untested so there might be further kinks to work out. :-)

**Comment by coeure-d-elephante** [comment]
Alright! All issues above were resolved. Thank you! 

Issue #3
I made a design change: Check box to radio. The radios are working fine and are displaying the right value:

- include_tax
- exclude_tax

Although I would like to preselect include_tax as default. 

However, the success values are not appearing ``` $net_total and $gross_total``` 

I suspect there's something wrong with my logic when displaying error and success messages. Almost done, I just need a bit of help.

2 issues:
1. Set Sales Tax radio to default
2. Display $net_total if $tax = include_tax and $gross_total if $tax = exclude_tax

from AppController.php

```php
$tax= $request->input('tax', 'include_tax');
```

http://e15p2.ssjavier.world/

```php
 <fieldset>
            <label>7.25% Sales Tax (California)</label>
                <input 
                type="radio" 
               name="tax"  
               id="include_tax" 
               value="include_tax"
               {{(!isset($price) OR is_null($tax)) ? 'checked' : '' }}
                >
                <br>
            <label>Exclude Sales Tax</label>
                <input 
                type="radio" 
                name="tax" 
                id="exclude_tax"      
                value="exclude_tax"
                {{ ($tax = 'exclude_tax') ? 'checked' : '' }}
                >
        </fieldset>

        <button type='submit' class='btn btn-primary'>Submit</button>
    </form>

    @if (!isset($price))
        <div class='results alert alert-warning'>
            Please enter appropriate values.
        </div>
    @else
        @if ($tax == 'include_tax')
        <div class='results alert alert-primary'>
            <div>
                <label for='net_total'>$ Net Total</label>
                <input type='number' name='net_total' id='net_total' value='{{ $net_total }}'>
            </div>
        </div>
            @else
             <div class='results alert alert-primary'>
            <div>
                <label for='net_total'>$ Gross Total</label>
                <input type='number' name='gross_total' id='gross_total' value='{{ $gross_total }}'>
            </div>
        </div>
        @endif
    @endif

```

**Comment by susanBuck** [comment]
For the radio button selection issue, in this line:

```php
{{ ($tax = 'exclude_tax') ? 'checked' : '' }}
```

You need to use a `==` comparison operator instead of the `=` assignment operator. The `=` operator will always evaluate to true which is why your second radio is always checked.

Looking at the second issue now and will reply again shortly.

**Comment by susanBuck** [comment]
For the second problem:

In [index.blade.php#L53](https://github.com/coeure-d-elephante/e15/blob/main/p2/resources/views/pages/index.blade.php#L53) you're referencing a variable `$price` but it's never passed to the view. 

Make sure it's one of the values extracted from the session and passed to the view in your AppController@index method:

```php
public function index()
    {
        return view('pages/index')->with([
            'net_total' => session('net_total', null),
            'sales_tax' => session('sales_tax', null),
            'gross_total' => session('gross_total', null),
            'tax'=> session('tax', null)
        ]);
    }
```

Additionally, when checking if price is 0, use the `==` comparison operator, not the `=` assignment operator. So this line:

```php
@if (!isset($price) or $price = 0)
```

Should be:
```php
@if (!isset($price) or $price == 0)
```

**Comment by coeure-d-elephante** [comment]
Alright thank you. 

For the radio button selection:
I did have the "==" operator initially, however, it was erring before due to faulty logic.  It's fixed now how it should. Thank you. 


However, rendering the proper notification for error and successful inputs still doesn't work. 

```php
<fieldset>
            <label>7.25% Sales Tax (California)</label>
            <input type="radio" name="tax" id="include_tax" value="include_tax"
                {{ (!isset($price) or is_null($tax)) ? 'checked' : '' }}>
            <br>
            <label>Exclude Sales Tax</label>
            <input type="radio" name="tax" id="exclude_tax" value="exclude_tax"
                {{ $tax == 'exclude_tax' ? 'checked' : '' }}>
        </fieldset>

        <button type='submit' class='btn btn-primary'>Submit</button>
    </form>

    @if (!isset($price) or $price == 0)
            <div class='results alert alert-warning'>
                Please enter appropriate values.
            </div>
    @else
        @if (isset($price) && $tax == 'include_tax')
            <div class='results alert alert-primary'>
                <div>
                    <label for='net_total'>$ Net Total</label>
                    <input type='number' name='net_total' id='net_total' value='{{ $net_total }}'>
                </div>
            </div>
        @else
            @if(isset($price) && $tax == 'exclude_tax')
            <div class='results alert alert-primary'>
                <div>
                    <label for='gross_total'>$ Gross Total</label>
                    <input type='number' name='gross_total' id='gross_total' value='{{ $gross_total }}'>
                </div>
            </div>
        @endif
        @endif
    @endif

```

From AppController.php

```php
 public function index()
    {
        return view('pages/index')->with([
            'net_total' => session('net_total', null),
            'sales_tax' => session('sales_tax', null),
            'gross_total' => session('gross_total', null),
            'tax'=> session('tax', null)
        ]);
    }

  public function calculate(Request $request)
    {
        $request->validate([
         'price'=> 'required',
         'discount'=>'required'
        ]);

        $price = $request->input('price', '');
        $discount = $request->input('discount', '');
        $tax= $request->input('tax', 'include_tax');
        

        dump($tax);
       
        $sales_tax = .0725;

        // //  dump('inputs:', $price, $discount, $sales_tax);
        
        // //convert percent to decimal
        $float = floatval($discount)/100;

        $apply_discount_price = $price * $float;
     
        $gross_total = $price - $apply_discount_price;   

        $tax_amount = $gross_total * $sales_tax;

        $net_total = $gross_total + $tax_amount;

        // dump([
        //     'Price after discount:',$gross_total, 
        //     'Tax amount for item:',
        //     $tax_amount, 
        //     'Grand total with discount and tax:', $net_total
        // ]);

        return redirect('/')->with([
         'net_total' => $net_total,
         'gross_total' => $gross_total,
         'price' => $price,
         'tax'=>$tax
        ]);
    }
}

```

This is the last issue with the project and will be submitted after fixed.

**Comment by susanBuck** [comment]
FYI - Looking at this now and will reply shortly.

**Comment by susanBuck** [comment]
Hi @coeure-d-elephante -

I was typing out a response but it started to be too much to type so I thought I'd do a quick video run through on some suggestions for your code : )

Video: https://www.youtube.com/embed/voGqgvjh57c?rel=0&showinfo=0 (FYI check back shortly if it says it's still processing - I just uploaded it)

Here's the code examples I showed in the video: https://gist.github.com/susanBuck/13863063ed331163bfc25aed4865886b

Let me know if you have any follow-up questions.

**Comment by coeure-d-elephante** [comment]
All feedback received and replied via email. 

Thank you very much Susan! 😊
