### ISSUE TITLE
Git error when pushing and merging changes

### ISSUE THREAD

**Issue by coeure-d-elephante** [susanBuck/e15-spring23#28]
<img width="845" alt="Screenshot 2023-04-23 at 18 42 43" src="https://user-images.githubusercontent.com/78046295/233880993-0077cf70-f1ec-4151-b0f9-7ff76cd9e489.png">

<img width="1223" alt="Screenshot 2023-04-23 at 18 43 00" src="https://user-images.githubusercontent.com/78046295/233880998-e3106188-de86-4806-8900-901fef7756b0.png">

<img width="701" alt="Screenshot 2023-04-23 at 18 46 05" src="https://user-images.githubusercontent.com/78046295/233881267-b970665f-a6b8-41cc-9930-d03fc5ecd1a6.png">

Since I created the prod version of e-15, I've been encountering this problem whenever I attempt to push my code and merge onto my branch. I'm a little bit confused on how to follow the hints suggested from the git-error

**Comment by susanBuck** [comment]
Hi @coeure-d-elephante - I'm logging into your server now to investigate and will reply with more details shortly.

**Comment by susanBuck** [comment]
Here's my understanding of what's going on:

When we created the production version of our application, we cloned another copy of your e15 repository to our servers (located at `/var/www/e15-prod`). 

It looks like within that copy, you made changes, committed them (**2 commits total**), and pushed them to the main e15 repository at Github. 

When you did that the original dev copy of your e15 repository (located at `/var/www/e15/`) on the server was now out of sync with things.

Likewise, it looks like changes/commits (**4 commits total**) were made in the `/var/www/e15/` repository.

That's why the sync button has 2 down and 4 up. It wants you to pull the 2 commits and push the 4 commits.
<img width="337" alt="image" src="https://user-images.githubusercontent.com/237711/234040522-aca9f075-757e-44a8-9ca5-8a38a04d71f1.png">

When you do that, though, we get this output:

```
> git pull --tags origin main
From github.com:coeure-d-elephante/e15
 * branch            main       -> FETCH_HEAD
hint: You have divergent branches and need to specify how to reconcile them.
hint: You can do so by running one of the following commands sometime before
hint: your next pull:
hint: 
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
fatal: Need to specify how to reconcile divergent branches.
```

To resolve this, I ran `git pull --no-rebase` from within your development repository to merge the divergent commits. Output:

```
Merge made by the 'ort' strategy.
 .../database/migrations/2023_04_09_043145_create_books_table.php  | 39 +++++++++++++++++++++++++++++++
 .../2023_04_09_045026_add_page_count_column_to_books_table.php    | 32 +++++++++++++++++++++++++
 2 files changed, 71 insertions(+)
 create mode 100644 bookmark/database/migrations/2023_04_09_043145_create_books_table.php
 create mode 100644 bookmark/database/migrations/2023_04_09_045026_add_page_count_column_to_books_table.php
```

Then, I was able to run `git push`:

```
Enumerating objects: 199, done.
Counting objects: 100% (161/161), done.
Compressing objects: 100% (111/111), done.
Writing objects: 100% (117/117), 25.48 KiB | 318.00 KiB/s, done.
Total 117 (delta 65), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (65/65), completed with 32 local objects.
To github.com:coeure-d-elephante/e15.git
   13a31c1..f2b8231  main -> main
```

And finally, I switched over to the `/var/www/e15-prod` directory to do a `git pull` so it was in sync with the changes I had just pushed from `/var/www/e15/`.

And with that, everything is in sync and you shouldn't have any problems pushing commits from `/var/www/e15`.

Moving forward, to avoid this sort of issue, you typically should not make code changes in the production `/var/www/e15-prod`. Consider it a "read-only" copy of your code base. Any code changes should happen in dev (`/var/www/e15`). The way production should get changes is by pulling them from Github after they've been pushed there by dev.

Let me know if you have any follow-up questions about the above.  :)

**Comment by coeure-d-elephante** [comment]
@susanBuck Hi! Sorry for the delayed reply but that all makes sense, thank you! I'll make sure to never do changes on the prod version of my projects from this point onward.

**Comment by coeure-d-elephante** [comment]
Actually I do have a question: 
How did you know to do the command "git pull --no rebase" instead of "rebase". What's the difference between the two?

**Comment by susanBuck** [comment]
I went with `--no-rebase` so it would use merge, just because it listed merge as the default strategy. I looked up the difference between the two (details below) and didn't see anything notable for our workflow setup - in other words, both would have worked to resolve the divergence.

> In Git, both merge and rebase are used to combine changes from one branch into another branch. However, they differ in the way they apply those changes to the target branch.
> 
> Merge:
> 
> When you merge a branch into another branch, Git creates a new commit that has two parent commits, one from each branch. This new commit represents the merge and contains the combined changes from both branches. The result is a branch that has a linear history, with the new merge commit forming a new branch point.
> 
> In other words, merge combines the changes from the source branch into the target branch and creates a new commit that represents the merge. This commit has two parent commits, one from the target branch and one from the source branch.
> 
> Rebase:
> 
> When you rebase a branch onto another branch, Git applies the changes from the source branch directly onto the target branch, one commit at a time. This results in a new sequence of commits that appears as if the changes were made directly on the target branch, without any intermediate merge commits.
> 
> In other words, rebase takes the changes from the source branch and applies them on top of the target branch, essentially rewriting the target branch's history to include the changes from the source branch.
> 
> The key difference between merge and rebase is that merge preserves the history of both branches, while rebase rewrites the history of the source branch onto the target branch.
> 
> In general, merge is preferred when you want to preserve the history of both branches, while rebase is preferred when you want a cleaner, linear history that appears as if the changes were made directly on the target branch. However, it's important to note that rebase should only be used on local branches that haven't been shared with others, while merge is typically used for integrating changes from shared branches.
>
