### ISSUE TITLE
Testing tools

### ISSUE THREAD

**Issue by bar181** [susanBuck/e15-spring23#29]
Just wondering about different testing tools.  

The video mentions Dusk is a good tool if you develop locally and Codeception is good for everything except javascript-heavy sites.

Any thoughts for Laravel projects that have frontend frameworks like Vue.js? 

Also, should you run different tests with different tools (e.g. HTTP Tests for an API, Codeception for user workflow and Dusk for Vue interactions) or is it better to use one primary tool?

**Comment by susanBuck** [comment]
If you're building a JS heavy site with a framework frontend like Vue.js, I'd definitely suggest digging into Dusk. 

It's common to have different test tools for different *types* of testing, but less common to use different test tools for the same type of tests. For example, running both Codeception and Dusk for browser based testing is a bit redundant and adds extra complexity in terms of working within two different systems. That being said, if you had a very large app, there could be an argument for testing non-JS stuff with Codeception since it's so fast, and reserving Dusk for the JS-required stuff.
