### ISSUE TITLE
phpmyadmin - still seeing errors after upgrading PHP

### ISSUE THREAD

**Issue by bar181** [susanBuck/e15-spring23#34]
I upgrade PHP and Laravel per video today.  
Wondering how to upgrade so we don't see errors in phpMyAdmin?

**Comment by susanBuck** [comment]
You'll need to upgrade phpMyAdmin. I looked into it and it looks like when we installed it via apt, its getting an outdated version (4.9.5). Given this, we need to manually install it so we can grab the latest version.

To do this, first run `sudo apt-get purge phpmyadmin` to remove the existing install.

Then run `rm /var/www/html/phpmyadmin` to remove the symbolic link we set up to make the existing install accessible.

Next, run the following command to download the latest version (`5.2.1`) from the phpmyadmin website:

```bash
> wget https://files.phpmyadmin.net/phpMyAdmin/5.2.1/phpMyAdmin-5.2.1-all-languages.tar.gz
```

Unzip the resulting download:

```bash
> tar -xvzf phpMyAdmin-5.2.1-all-languages.tar.gz
```

Move the resulting directory to our web accessible directory, `/var/www/html`:

```bash
> sudo mv phpMyAdmin-5.2.1-all-languages /var/www/html/phpmyadmin
```

Set the appropriate permissions on this directory:

```bash
> sudo chown -R www-data:www-data /var/www/html/phpmyadmin
```

Finally, open your default DigitalOcean sites config,`/etc/nginx/sites-available/digitalocean` and update the reference of `php8.0-fpm` to `php8.2-fpm` so that phpMyAdmin is loaded using php 8.2 instead of 8.0.

Restart your server:

```bash
> systemctl restart nginx
``` 

And test it out via `yourdomain.com/phpmyadmin`. Looking at the details on the homepage of phpmyadmin, you should see it report php version 8.2 and phpmyadmin version 5.2.1.

<img width="1110" alt="image" src="https://user-images.githubusercontent.com/237711/235823772-3c66cea4-9e7f-4aaa-9d8d-c189a9c6b4b7.png">
