### ISSUE TITLE
Undefined type 'Laravel\Fortify\Fortify'

### ISSUE THREAD

**Issue by sicwere** [susanBuck/e15-spring23#35]
I installed Fortify in my p3 project, and create a service provider for it, but I'm getting the error `Undefined type 'Laravel\Fortify\Fortify'`. Please see the attached screenshot for more detail.
![fortify](https://user-images.githubusercontent.com/11153087/236361357-58b479c2-7a34-486a-9374-036c7fe5052d.png)

**Comment by susanBuck** [comment]
Can you try restarting VSCode? I've seen this happen before and usually a restart resolves it. If not, let me know.

**Comment by sicwere** [comment]
I restated VSCode, and the problem remains.

**Comment by sicwere** [comment]
Although the error message persists, Fortify actually does work on my site.

**Comment by susanBuck** [comment]
Thanks for trying the "low hanging fruit" of restarting. : ) I'm going to clone your project now to see if I can recreate. Will reply shortly with what I find out.

**Comment by susanBuck** [comment]
I just logged into your server to take a lot and am not seeing the errors (screenshot for reference below). Can you confirm you're still seeing the issue on your end? When I've seen this in the past, it was always just that VSCode was having a hiccup in mapping the classes, not that there was an actual problem in the code. That's why I had you try restarting and why you're finding that Fortify is working fine besides the errors.

Curious if you're still seeing it on your end.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/237711/236644070-bb1c697f-ca1f-42c2-b176-ecea1d15935c.png">
