### ISSUE TITLE
Caused issues by installing certbot to run SSL on p3

### ISSUE THREAD

**Issue by traveler9878** [susanBuck/e15-spring23#37]
I installed certbot and was running ssl on p3 and due to the auth errors tried to remove the ssl from the nginx configuration manually and some other things.  Running into a downward spiral over the composer update failure.  Appears to me to be a compatibility issue between the new release of Laravel and the composer update for fortify.  The only thing still working for me is my bookmark app and it wont authenticate because of the composer dependency being removed.

**Comment by traveler9878** [comment]
I removed most of the configuration from my HES file and reinstalled certbot with the instructions not to redirect from port 80 to 444 for e15p3.  That part seems to be working, but.. the auth isn't working in bookmark due to the composer update incompatibility with Laravel 10 and I'm getting a 403 on a root request and a 404 on a specific request for my other sites.  Taking a break.

**Comment by susanBuck** [comment]
[See my reply on #36...](https://github.com/susanBuck/e15-spring23/issues/36#issuecomment-1537210928)

**Comment by susanBuck** [comment]
Circling back to the SSL issue specifically, if I recall correctly, you had something like this in the site config:

```
server {
    listen 80;
    listen [::]:80;
    server_name e15p3.davidcurtis.me;
    root /var/www/e15/p3/;

    [...other server config code here...]

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/e15p3.davidcurtis.me/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/e15p3.davidcurtis.me/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}
```

The problem with this is it's trying to listen on two different ports - both `80` (which is for `http`) and `443` (for `https`). To address this, when wishing to use `https`, remove the two lines making reference to port `80`.

But to simplify things, because HTTPS/SSL is not a project requirement, I suggest tabling it for now. Get everything else working as expected, and then time permitting tackle it. You could even tackle it after p3 is submitted/graded - happy to assist/answer questions even after the semester is over.

This is not to devalue the importance of HTTPS/SSL, just don't want it interfering with project requirements. : )

Side note: For anyone else reading this thread and interested in HTTPS/SSL, here are a couple videos to check out:

+ [What is HTTPS (SSL) and why every site should use it](https://www.youtube.com/watch?v=J0d28jltHCQ)
+ [HTTPS / SSL via “Let’s Encrypt” on a Nginx Web Server](https://www.youtube.com/watch?v=MVuJ5h2YQoQ)

**Comment by traveler9878** [comment]
Yes definitely not making any unnecessary changes prior to grading of P3…

I think I’m covered on my minimum 2 distinct features by requiring login
and the soft delete…. I am honk my P3 is significantly different from
bookmark to quality as a from scratch simple reference app.

I’ll be glad when the tests are completed.

Thanks again.

**Comment by susanBuck** [comment]
FYI Because login was directly addressed in lecture/notes and the Bookmark example, that alone would not be counted as a unique feature.
